import { v4 as uuidv4 } from 'uuid';
import type { ProjectState, Painting, PackUUIDs, Source } from './types';
import { ProjectSchema } from './schema';
import { generatePaintingSlug } from './slug';

export function createEmptyProject(): ProjectState {
  return {
    version: 1,
    pack: {
      name: 'My Paintings',
      description: 'Custom paintings generated by MC Painting Maker.',
      namespace: 'paintings',
      semver: [1, 0, 0],
      minEngineVersion: [1, 21, 30],
      iconPngBase64: null,
      creativeGroupName: 'Custom Paintings',
    },
    // Identity is assigned lazily on the first image load via ensurePackUUIDs.
    uuids: {
      bpHeader: '',
      bpModule: '',
      bpScriptModule: '',
      rpHeader: '',
      rpModule: '',
    },
    paintings: [],
  };
}

// Returns a new ProjectState with any empty UUIDs filled with fresh uuidv4 values.
// Idempotent: if all UUIDs are already set, the input is returned unchanged.
export function ensurePackUUIDs(state: ProjectState): ProjectState {
  const u = state.uuids;
  const allSet = u.bpHeader && u.bpModule && u.bpScriptModule && u.rpHeader && u.rpModule;
  if (allSet) return state;
  const next: PackUUIDs = {
    bpHeader: u.bpHeader || uuidv4(),
    bpModule: u.bpModule || uuidv4(),
    bpScriptModule: u.bpScriptModule || uuidv4(),
    rpHeader: u.rpHeader || uuidv4(),
    rpModule: u.rpModule || uuidv4(),
  };
  return { ...state, uuids: next };
}

export function createPaintingFromImage(
  name: string,
  source: Source,
): Painting {
  const ratio = source.naturalW / source.naturalH;
  const maxLong = 64;
  let w16: number, h16: number;
  if (ratio >= 1) {
    w16 = maxLong;
    h16 = Math.max(16, Math.round((maxLong / ratio) / 16) * 16);
  } else {
    h16 = maxLong;
    w16 = Math.max(16, Math.round((maxLong * ratio) / 16) * 16);
  }
  const id = uuidv4();
  return {
    id,
    name,
    slug: generatePaintingSlug(name, id),
    canvasW16: w16,
    canvasH16: h16,
    source,
    transform: { x16: 0, y16: 0, w16, h16, rotation: 0, flipX: false, flipY: false },
    resampling: 'smooth',
    textureDensity: 'auto',
    material: 'alphatest',
  };
}

export function migrate(state: unknown): ProjectState {
  if (typeof state !== 'object' || state === null || !('version' in state)) {
    throw new Error('Invalid project state: missing version');
  }
  const v = (state as { version: unknown }).version;
  if (v !== 1) throw new Error(`Unsupported project version: ${String(v)}`);
  // Slug was added after the first wave of projects. Backfill it from the current
  // name + id before validation so old saves keep working. Once set, slug never
  // changes, so this only runs on the migration boundary.
  const raw = state as { paintings?: Array<{ id?: unknown; name?: unknown; slug?: unknown }> };
  if (Array.isArray(raw.paintings)) {
    for (const p of raw.paintings) {
      if (p && typeof p === 'object' && (typeof p.slug !== 'string' || !p.slug)) {
        const id = typeof p.id === 'string' ? p.id : '';
        const name = typeof p.name === 'string' ? p.name : '';
        p.slug = generatePaintingSlug(name, id);
      }
    }
  }
  return ProjectSchema.parse(state);
}
