import { v4 as uuidv4 } from 'uuid';
import type { ProjectState, Painting, PackUUIDs, Source } from './types';
import { ProjectSchema } from './schema';
import { generatePaintingSlug, CURRENT_SLUG_VERSION } from './slug';

export function createEmptyProject(): ProjectState {
  return {
    // v3 ships the custom placer items. Legacy projects loaded from
    // localStorage keep their original version (2) and use spawn eggs.
    version: 3,
    pack: {
      name: 'My Paintings',
      description: 'Custom paintings generated by MC Painting Maker.',
      namespace: 'paintings',
      semver: [1, 0, 0],
      minEngineVersion: [1, 21, 30],
      iconPngBase64: null,
      creativeGroupName: 'Custom Paintings',
      autoBumpVersion: true,
    },
    // Identity is assigned lazily on the first image load via ensurePackUUIDs.
    uuids: {
      bpHeader: '',
      bpModule: '',
      bpScriptModule: '',
      rpHeader: '',
      rpModule: '',
    },
    paintings: [],
  };
}

// Returns a new ProjectState with any empty UUIDs filled with fresh uuidv4 values.
// Idempotent: if all UUIDs are already set, the input is returned unchanged.
export function ensurePackUUIDs(state: ProjectState): ProjectState {
  const u = state.uuids;
  const allSet = u.bpHeader && u.bpModule && u.bpScriptModule && u.rpHeader && u.rpModule;
  if (allSet) return state;
  const next: PackUUIDs = {
    bpHeader: u.bpHeader || uuidv4(),
    bpModule: u.bpModule || uuidv4(),
    bpScriptModule: u.bpScriptModule || uuidv4(),
    rpHeader: u.rpHeader || uuidv4(),
    rpModule: u.rpModule || uuidv4(),
  };
  return { ...state, uuids: next };
}

export function createPaintingFromImage(
  name: string,
  source: Source,
): Painting {
  const ratio = source.naturalW / source.naturalH;
  const maxLong = 64;
  let w16: number, h16: number;
  if (ratio >= 1) {
    w16 = maxLong;
    h16 = Math.max(1, Math.ceil(maxLong / ratio));
  } else {
    h16 = maxLong;
    w16 = Math.max(1, Math.ceil(maxLong * ratio));
  }
  const id = uuidv4();
  return {
    id,
    name,
    slug: generatePaintingSlug(name, id),
    slugVersion: CURRENT_SLUG_VERSION,
    slugLocked: false,
    canvasW16: w16,
    canvasH16: h16,
    source,
    transform: { x16: 0, y16: 0, w16, h16, rotation: 0, flipX: false, flipY: false },
    resampling: 'smooth',
    textureDensity: 'auto',
    material: 'alphatest',
  };
}

export function migrate(state: unknown): ProjectState {
  if (typeof state !== 'object' || state === null || !('version' in state)) {
    throw new Error('Invalid project state: missing version');
  }
  const s = state as {
    version: unknown;
    paintings?: Array<{
      id?: unknown; name?: unknown; slug?: unknown;
      slugVersion?: unknown; slugLocked?: unknown;
      canvasH16?: unknown;
      transform?: { y16?: unknown; h16?: unknown };
    }>;
  };
  const v = s.version;
  if (v !== 1 && v !== 2 && v !== 3) throw new Error(`Unsupported project version: ${String(v)}`);
  // Slug + slugVersion were added after the first wave of projects. Backfill from
  // the current name + id before validation. Once set, both fields are frozen, so
  // this only runs on the migration boundary. Paintings without slugVersion are
  // assumed v1 because that was the only algorithm before the field existed.
  // slugLocked defaults to true for legacy paintings so their existing slug is
  // preserved verbatim. New paintings created today default to false.
  if (Array.isArray(s.paintings)) {
    for (const p of s.paintings) {
      if (!p || typeof p !== 'object') continue;
      if (typeof p.slug !== 'string' || !p.slug) {
        const id = typeof p.id === 'string' ? p.id : '';
        const name = typeof p.name === 'string' ? p.name : '';
        p.slug = generatePaintingSlug(name, id);
      }
      if (typeof p.slugVersion !== 'number' || !Number.isInteger(p.slugVersion) || p.slugVersion < 1) {
        p.slugVersion = 1;
      }
      if (typeof p.slugLocked !== 'boolean') {
        p.slugLocked = true;
      }
    }
  }
  // v2 -> v3 is intentionally NOT auto-applied. v3 swaps auto spawn eggs for
  // custom entity_placer items, which changes the item identifiers that end up
  // in player inventories. Forcing the upgrade would silently invalidate hotbar
  // slots in worlds that already imported a v2 addon, so v2 projects stay v2
  // until the user creates a fresh project.
  // v1 -> v2: Y axis convention switched from Y-down (offset from top) to Y-up
  // (offset from bottom, Minecraft-style). Flip each transform's y16 so the
  // visual position of existing images is preserved across the upgrade.
  if (v === 1) {
    if (Array.isArray(s.paintings)) {
      for (const p of s.paintings) {
        const t = p?.transform;
        if (
          t &&
          typeof p.canvasH16 === 'number' &&
          typeof t.y16 === 'number' &&
          typeof t.h16 === 'number'
        ) {
          t.y16 = p.canvasH16 - t.y16 - t.h16;
        }
      }
    }
    s.version = 2;
  }
  return ProjectSchema.parse(state);
}
