import { v4 as uuidv4 } from 'uuid';
import type { ProjectState, Painting, Source } from './types';

export function createEmptyProject(): ProjectState {
  return {
    version: 1,
    pack: {
      name: 'My Paintings',
      description: 'Custom paintings generated by MC Painting Maker.',
      namespace: 'paintings',
      semver: [1, 0, 0],
      minEngineVersion: [1, 21, 30],
      iconPngBase64: null,
      creativeGroupName: 'Custom Paintings',
    },
    uuids: {
      bpHeader: uuidv4(),
      bpModule: uuidv4(),
      bpScriptModule: uuidv4(),
      rpHeader: uuidv4(),
      rpModule: uuidv4(),
    },
    paintings: [],
  };
}

export function createPaintingFromImage(
  name: string,
  source: Source,
): Painting {
  const ratio = source.naturalW / source.naturalH;
  const maxLong = 64;
  let w16: number, h16: number;
  if (ratio >= 1) {
    w16 = maxLong;
    h16 = Math.max(16, Math.round((maxLong / ratio) / 16) * 16);
  } else {
    h16 = maxLong;
    w16 = Math.max(16, Math.round((maxLong * ratio) / 16) * 16);
  }
  return {
    id: uuidv4(),
    name,
    canvasW16: w16,
    canvasH16: h16,
    source,
    transform: { x16: 0, y16: 0, w16, h16, rotation: 0, flipX: false, flipY: false },
    resampling: 'smooth',
    textureDensity: 'auto',
    material: 'alphatest',
  };
}

export function migrate(state: unknown): ProjectState {
  if (typeof state !== 'object' || state === null || !('version' in state)) {
    throw new Error('Invalid project state: missing version');
  }
  const v = (state as { version: unknown }).version;
  if (v !== 1) throw new Error(`Unsupported project version: ${String(v)}`);
  return state as ProjectState;
}
